site_name: Drops
site_url: https://eineruntervielen.github.io/drops/

repo_url: https://github.com/eineruntervielen/drops
repo_name: eineruntervielen/drops


nav:
  - Drops: index.md
  - Install: inst.md
  - How it works...: arch.md
  - Learn by example: learn/index.md
  - Flask and Drops: flask_and_drops.md
theme:
  name: material
  language: en
  logo: assets/drops.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: black
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - termynal

markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - attr_list
  - mdx_include:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js