site_name: Drops
site_url: https://eineruntervielen.github.io/drops/

repo_url: https://github.com/eineruntervielen/drops
repo_name: eineruntervielen/drops


nav:
  - Drops: index.md
  - How it works...: arch.md
  - Learn by example: learn/index.md
  - Flask and Drops: flask_and_drops.md


theme:
  name: material
  language: en
  logo: assets/drops.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: black
#    palette: #63E6BE
plugins:
  - termynal

markdown_extensions:
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - attr_list
  - mdx_include:
      base_path: docs
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js